title: SMS Speedrunning Guide
description: RTA Notes made by emrik542
theme: just-the-docs

url: https://emrik542.github.io/sms-speedrunning-guide

aux_links:
  Template Repository: https://github.com/emrik542/sms-speedrunning-guide
